export const headerNameMap: Record<string, string> = {
    "Output File Name:": "outputFile",
    "Database File:": "slopFile",
    "Specify solvent phase region:": "solventPhase",
    "Specify independent liq-vap saturation variable:": "lipVapSatVar",
    "Specify independent State Variables:": "independentStateVar",
    "Specify tabulation option(Baric, Thermal):": "tabulationBaricOption",
    "Would you like to use the univariant curve option? (i.e., calculate T(logK,P) or P(logK,T):": "univariantCurveOption",
    "Specify tabulation option(Chronic, Thermal):": "tabulationChoricOption",
    "Specify table-increment option:": "tableIncrement",
    "Specify univariant calculation option:": "univariantCalcOption"
}

export const headerValueMap: Record<string, string> = {
    "One-Phase Region": "0",
    "Liquid Vapor Saturation Curve": "1",
    "Temprature (degCel), density(H2O) (g/cc)": "0",
    "Temprature (degCel), pressure (bars)": "1",
    "Calculate ISOCHORIC (T) tables": "0",
    "Calculate ISOTHERMAL (D) tables": "1",
    "Yes": "0",
    "No": "1",
    "Calculate T (logK, isobars)": "0",
    "Calculate P (logK, isotherms)": "1",
    "Calculate ISOBARIC (P) tables": "0",
    "Temprature (degCel)": "0",
    "Pressure (bars)": "1",
    "Calculate tables having uniform increments": "0",
    "Calculate tables having unequal increments": "1",
}

export 
const resetMap: Record<string, string[]> = {
  "One-Phase Region": [
    "isLiquidVaporSaturationCurveSelected",
    "isTemperatureDensitySelected",
    "isTemperaturePressureSelected",
    "isPressureSelected",
    "isTemperatureSelected",
    "isCalculateIsochoricSelected",
    "isCalculateIsothermalSelected",
    "isCalculateIsoBaricSelected",
    "isUnivariantCurveYesSelected",
    "isUnivariantCurveNoSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
  ],
  "Liquid Vapor Saturation Curve": [
    "isOnePhaseRegionSelected",
    "isTemperatureDensitySelected",
    "isTemperaturePressureSelected",
    "isPressureSelected",
    "isTemperatureSelected",
    "isCalculateIsochoricSelected",
    "isCalculateIsothermalSelected",
    "isCalculateIsoBaricSelected",
    "isUnivariantCurveYesSelected",
    "isUnivariantCurveNoSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
  ],
  "Temprature (degCel), density(H2O) (g/cc)": [
    "isTemperaturePressureSelected",
    "isPressureSelected",
    "isTemperatureSelected",
    "isCalculateIsochoricSelected",
    "isCalculateIsothermalSelected",
    "isCalculateIsoBaricSelected",
    "isUnivariantCurveYesSelected",
    "isUnivariantCurveNoSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
  ],
  "Temprature (degCel), pressure (bars)": [
    "isTemperatureDensitySelected",
    "isPressureSelected",
    "isTemperatureSelected",
    "isCalculateIsochoricSelected",
    "isCalculateIsothermalSelected",
    "isCalculateIsoBaricSelected",
    "isUnivariantCurveYesSelected",
    "isUnivariantCurveNoSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
  ],
  "Calculate ISOCHORIC (T) tables": [
    "isCalculateIsothermalSelected",
    "isCalculateIsoBaricSelected",
    "isUnivariantCurveYesSelected",
    "isUnivariantCurveNoSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
  ],
  "Calculate ISOTHERMAL (D) tables": [
    "isCalculateIsochoricSelected",
    "isCalculateIsoBaricSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
  ],
  "Calculate ISOBARIC (P) tables": [
    "isCalculateIsothermalSelected",
    "isCalculateIsochoricSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
  ],
  Yes: [
    "isCalculateIsothermalSelected",
    "isCalculateIsoBaricSelected",
    "isCalculateIsochoricSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
    "isUnivariantCurveNoSelected",
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
  ],
  No: [
    "isCalculateIsoBaricSelected",
    "isCalculateIsothermalSelected",
    "isUnivariantCurveYesSelected",
    "isCalculateTSelected",
    "isCalculatePSelected",
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
  ],
  "Calculate T (logK, isobars)": [
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
    "isCalculatePSelected",
  ],
  "Calculate P (logK, isotherms)": [
    "isUniformIncrementSelected",
    "isUnequalIncrementSelected",
    "isCalculateTSelected",
  ],
  "Calculate tables having uniform increments": [
    "isUnequalIncrementSelected",
  ],
  "Calculate tables having unequal increments": [
    "isUniformIncrementSelected",
  ],
  "Temprature (degCel)": ["isPressureSelected"],
  "Pressure (bars)": ["isTemperatureSelected"],
};
